name: Docker Security CI

on:
  push:
    branches:
      - main

jobs:
  trivy-scan-and-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Trivy scan Dockerfile
      - name: Trivy scan Dockerfile
        uses: aquasecurity/trivy-action@69cbbc0cbbf6a2b0bab8dcf0e9f2d7ead08e87e4
        with:
          scan-type: 'dockerfile'
          format: 'json'
          output: 'dockerfile-report.json'
          dockerfile: 'Dockerfile'

      # Step 3: Set up Docker with containerd BuildKit
      - name: Set up Docker (with containerd BuildKit)
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "experimental": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      # Step 4: Build Docker image locally
      - name: Build Docker image
        run: |
          docker buildx build --load -t local/pythonbaseimage:latest .
          docker images | grep pythonbaseimage

      # Step 5: Get Docker socket path
      - name: Get Docker socket path
        run: |
          url=$(docker context inspect | jq -r '.[0].Endpoints.docker.Host')
          socket_path=$(echo "$url" | awk -F// '{print $2}')
          echo "SOCKET=$socket_path" >> $GITHUB_ENV
          echo "Using Docker socket at: $socket_path"

      # Step 6: Patch image with Copacetic
      - name: Run Copa action
        uses: project-copacetic/copa-action@v1.2.1
        with:
          image: "local/pythonbaseimage:latest"
          image-report: "dockerfile-report.json"
          patched-tag: "patched"
          timeout: 5m
          custom-socket: ${SOCKET}
          output: out.json

      # Step 7: Final image check
      - name: Final image check
        run: |
          echo "Images after patching:"
          docker images | grep pythonbaseimage
